### ISSUE TITLE
Exception in Camera streaming

### ISSUE THREAD

**Issue by sarathrda** [LogmeinRescue/Android-SDK#10]
The attached file has the exception details, which occurs quite inconsistently after the Camera streaming is started. 

The file is [here](https://github.com/LogmeinRescue/Android-SDK/files/1894567/log_me_in_error.txt).

**Comment by tbalogh** [comment]
Dear Sarath,

We will review this issue and get in touch with you shortly.

Thank you for bringing this to our attention.

Tamas

**Comment by balazsbanyai** [comment]
Hi, 

We've just released a new version (3.2.4) that should address this issue. Please report back if the new version works for you. We will keep in touch regarding the other issues that you've raised.

Thank you very much,
Balazs

**Comment by sarathrda** [comment]
Hi @balazsbanyai ,

We were able to verify the fix for the Issue and it is working fine.

Thanks for the update.

**Comment by balazsbanyai** [comment]
Thank you very much!
