### ISSUE TITLE
Camera Streaming Issue

### ISSUE THREAD

**Issue by sarathrda** [LogmeinRescue/Android-SDK#20]
The Camera streaming is blank, if the Technician pauses and resumes the session.

**Steps to Reproduce**
1. Initiate the App Scree Sharing session
2. Accept the Incoming request in the Technician console
3. Notice that App screen is streamed successfully
4. Close the Session
5. Now start Camera Streaming session
6. Accept the Incoming request in the Technician console
7. Pause and Unpause the session in the Technician console
8. The Camera View on the device has blank screen, but the camera is streaming as per Technician portal.

**Expected Outcomes**
User should see the camera view in the app

**Actual Outcome**
User  is unable see the camera view in the app

**Other information**
The whole session video is available [here](https://rdalabs-my.sharepoint.com/:v:/p/hkumar/ERUagPXrS21PluSJBFoxtUIBXfwG8Lt8HV_eLScq2fvMnQ?e=vI8n8M)

**Comment by balazsbanyai** [comment]
Hi, 

The video that you provided shows only the camera streaming session, but I think I understand what is the issue, please verify:

So when the camera streaming session is resumed by the technician from HOLD state, the streaming on the mobile device will not continue, unless you pause-resume the the rendering on the mobile device itself, right?

Thank you very much, Balazs

**Comment by sarathrda** [comment]
> So when the camera streaming session is resumed by the technician from HOLD state, the streaming on the mobile device will not continue, unless you pause-resume the rendering on the mobile device itself, right?

Exactly!

**Comment by balazsbanyai** [comment]
We'll look into it, and keep you posted!

Thank you!

**Comment by rachitasingh1209** [comment]
@balazsbanyai do we have any update on this issue? We are trying to wrap up all open issues as soon as possible this week. cc @sarathrda

**Comment by rachitasingh1209** [comment]
@balazsbanyai We came across this open issue and wanted to follow up with you. Do you have any update on this? We are trying to resolve all open issues related to LMI before end of next week. cc @sarathrda

**Comment by tbalogh** [comment]
Hi @rachitasingh1209,

We'll review this issue and get back you soon.

**Comment by tamasgyongyosi** [comment]
Hi @rachitasingh1209,

Unfortunately we were unable to reproduce this bug neither with the SDK version number 3.2.6 or 3.4.0.
Could you verify that the issue is still exist with the latest version? Are there any other step to help us reproducing this issue?

Please find the attached video about how we try to reproduce the issue:
[test.zip](https://github.com/LogmeinRescue/Android-SDK/files/3461039/test.zip)

**Comment by sarathrda** [comment]
Hi @tamasgyongyosi We have verified the bug with the latest version. And it seems that it is working as expected, and we are not able to reproduce the same.

You can close this issue.

Thanks. cc: @rachitasingh1209

**Comment by tbalogh** [comment]
We are happy to here that @sarathrda.
