### ISSUE TITLE
Application Lifecyccle callback Issue

### ISSUE THREAD

**Issue by sarathrda** [LogmeinRescue/Android-SDK#21]
App lifecycle callback is handled properly fpr App Screen Streaming, only if `          RescueSDK.initializeLifecycleReporter(application)` is called in Application class, but not in any other Android component with a valid instance of the Application class as follows:

`RescueSDK.initializeLifecycleReporter((Application)getApplicationContext())`

**Steps to Reproduce**
- From Technician Console start the session
- In Mobile, let the app be in foreground
- Once the session starts, in Technician control it says " Customer has sent app to background."

**Expected Outcomes**
Technician should be able to view the app screen in  LogMeIn-Console

**Actual Outcome**
Technician is not  able to view the app screen in  LogMeIn-Console

**Other information**
The whole session video is avalble [here](https://rdalabs-my.sharepoint.com/:v:/p/hkumar/EW7B52ykMA5Ho2kaI_VDIWEBHYoJW7F2x1Eot4JoMcjoDg?e=FLcYMr)

**Comment by balazsbanyai** [comment]
Hello, 

The behavior that you described is expected. 

As the [documentation](https://logmeinrescue.github.io/Android-SDK/#4) says: You **must** use the following snippet in your application's onCreate method:
`public class MyApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        RescueSDK.initializeLifecycleReporter(this);
    }
}`

The reason for this lies in the machinery of the Android applications themselves: If you don't listen to the lifecycle callbacks from the very first moment that the application is started, then the lifecycle tracker will not be able to track the started and finished activities properly.

Please call the described method in your application's onCreate method.
