### ISSUE TITLE
Camera Share Crashes with 64-bit Devices

### ISSUE THREAD

**Issue by jensulc** [LogmeinRescue/Android-SDK#22]
We recently included an abiFilter in the build.gradle file for arm64-v8a devices to have 64-bit devices explicitly leverage the 64-bit .so libraries from another vendor.  This has in turned cause a crash when opening the camera share functionality.  We’re getting a runtime error where the libMediaClient.so library can’t be found.  I’ve pasted the entire stacktrace below for more information.  Do you have an sdk version that supports 64-bit devices?

![image](https://user-images.githubusercontent.com/34034740/54606281-c7531d80-4a21-11e9-9b10-9704138e2ea7.png)

**Comment by zbodogh** [comment]
Dear jensulc,

Currently 64-bit isn't supported. It's on our roadmap, expected around mid-summer.

Best Regards,
Zsolt

**Comment by jensulc** [comment]
@zbodogh do you have a suggested workaround for 64-bit devices?

**Comment by tbalogh** [comment]
Hi Jensulc,

Thank you for reporting this issue. At the moment we do not have a suggested workaround. We will revisit the issue if we can come up a solution earlier.

Bets,
Tamas

**Comment by tbalogh** [comment]
@jensulc We've just released a new version (3.4.0) that contains the 64-bit support. Please report back if the new version works for you.

**Comment by tbalogh** [comment]
@jensulc We've just released a new version (3.4.0) that contains the 64-bit support. Please report back if the new version works for you.

**Comment by nripoli4810** [comment]
Hi @tbalogh, @jensulc has moved to a different team and I've taken over the project where this ticket originated. This issue has been resolved and we'll open a new issue should we encounter anything else. Thanks!
