### ISSUE TITLE
Remote Control

### ISSUE THREAD

**Issue by voliverio** [LogmeinRescue/Android-SDK#26]
Hi,

As requested in issue #25 I'm creating a new issue.

I'm trying to remote control a device using the SDK but I'm not able to do it, a message in the Technician Console says "Configurations in the remote device are preventing the inicialization of the remote control"

Here are the device information shown in the technician console:
OS Version: Android 7.1.1
Base Version: J250MUBS5ASE1
Compilation: NMF26X.J250MUBS5ASE1

Thank you.

**Comment by tamasgyongyosi** [comment]
Hi @voliverio,

We'll review this issue and get back you soon.

**Comment by tamasgyongyosi** [comment]
Hi @voliverio,

Please be aware what @tbalogh described about the Remote Control in [#25 ](https://github.com/LogmeinRescue/Android-SDK/issues/25#issuecomment-513814012) was incorrect. There is no Remote Control capability exposed to the Rescue SDK.

We investigate adding Remote Control capability only to AppScreenStreamingExtension as we think that it can be useful in case of supporting your application directly (without leaving your app).

Could it work for you? Also it would be a great help to us if you could describe your use case where Remote Control would be useful.

Please let us know if you have further questions.

**Comment by tbalogh** [comment]
Hi @voliverio ,

I know it's been a while, but **we recently added an _In-App Remote Control_ feature to the SDK**. The _In-App Remote Control_ feature enables the Technician to remotely control the embedder application while the embedder application is in the foreground. You can find the details in the [developer guide](https://logmeinrescue.github.io/Android-SDK/#11. ).

Please be aware, that the _In-App Remote Control_ feature enables the Technicain to control the device only while the embedder application is in the foreground, but the Technician immediatly lost control, when the embedder application goes into the background. 

Hope this feature can empower your application.

Best,
Tamas
