### ISSUE TITLE
Camera Share, Customer has sent app to background.

### ISSUE THREAD

**Issue by AvoChris** [LogmeinRescue/Android-SDK#46]
Hi,

I'm having an issue with the camera sharing, no matter what I do with the CameraStreamView, it will tell me customer has sent app to background on the technician console.

I can see the blurred camera view on the device when the session is connecting and then a clear view when the session has connected, but I cannot see the camera view in the console due to the customer has sent app to background issue. So it seems the connection is working but not detecting that the camera view is the front most view on the screen.

I have tried this:

camera_stream_view.visibility = View.VISIBLE
cameraExtension.startRendering(camera_stream_view)
camera_stream_view.bringToFront()

and this:

camera_stream_view.visibility = View.VISIBLE
camera_stream_view.bringToFront()
cameraExtension.startRendering(camera_stream_view)

but it always shows that error. Any ideas?

**Comment by tbalogh** [comment]
Hi Chris,

Could you verify, that _RescueSDK.initializeLifecycleReporter(this);_ was called in the application's onCreate method, as described [here](https://logmeinrescue.github.io/Android-SDK/#4)?

Best,
Tamas

**Comment by AvoChris** [comment]
We have called _RescueSDK.initializeLifecycleReporter(application)_ (Kotlin), could the issue be that it extends AppCompatActivity instead of application?

**Comment by tbalogh** [comment]
This could be the issue. You **must** call this in your application's onCreate method in order to enable the RescueSDK to track the app background/foreground state.

**Comment by tbalogh** [comment]
Let us know, if calling _RescueSDK.initializeLifecycleReporter(application)_ in your application's onCreate resolves the issue or if you have any further question.

**Comment by AvoChris** [comment]
I am just awaiting a technician to assist me with testing. Will update ASAP.

**Comment by AvoChris** [comment]
I am happy to say that it is now working, thank you for the response!
