### ISSUE TITLE
Whiteboard annotations disappear over some system apps during screen share

### ISSUE THREAD

**Issue by cswagner** [LogmeinRescue/Android-SDK#51]
During a screen share session, the whiteboard annotations disappear when some system apps are brought to the foreground. We started noticing this as of Android 10. For an example, please see [this video](https://slack-files.com/T02DPSXQC-F022V3875T2-7b30649b15) which shows the whiteboard annotations disappearing over the Android system settings app on Android 11.

Steps to reproduce:
- Start a screen share session on a device running at least Android 10
- Enable whiteboard annotations and add some to the screen share
- Open the Android system settings app
- Whiteboard annotations disappear
- Navigate out of the Android system settings app
- Whiteboard annotations reappear

Running `adb shell dumpsys window windows`, it looks like there's a hidden, system-level flag - `HIDE_NON_SYSTEM_OVERLAY_WINDOWS` - on the Android system settings window that will cause any other window that requires `SYSTEM_ALERT_WINDOW` to be hidden while that window is visible:
```
Window #6 Window{7ddc0ef u0 com.android.settings/com.android.settings.Settings}:
    mDisplayId=0 rootTaskId=8502 mSession=Session{1044e91 16661:1000} mClient=android.os.BinderProxy@5c729ce
    mOwnerUid=1000 showForAllUsers=false package=com.android.settings appop=NONE
    mAttrs={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x10302f2
      fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
      pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND HIDE_NON_SYSTEM_OVERLAY_WINDOWS FIT_INSETS_CONTROLLED
      vsysui=LAYOUT_STABLE LAYOUT_HIDE_NAVIGATION LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR
      apr=LIGHT_STATUS_BARS LIGHT_NAVIGATION_BARS
      fitSides=}
```

From the same command, we see a note about the Android system settings app hiding system alert windows:
```
Hiding System Alert Windows:
  #0 Window{7ddc0ef u0 com.android.settings/com.android.settings.Settings}:
```

Since the cause seems external to this SDK, I'm not sure if there's anything that can be done here. Perhaps this could be noted in the documentation/codelab?

**Comment by tamasgyongyosi** [comment]
Hi @cswagner ,

Nice catch :) Although I think that we can't do anything about this flag. We will mention this limitation in the codelab.
