### ISSUE TITLE
Flutter widget is not visible in technician console.

### ISSUE THREAD

**Issue by Ritheesh36** [LogmeinRescue/Android-SDK#53]
We have integrated Rescue SDK in Android and able to do chat and screen sharing functionality.  

When we use the remote control option in the rescue console, the screen is not visible and getting a black screen.

We have identified, it's working in the Native Android widget but not in the flutter widget.

**Comment by tbalogh** [comment]
Hi @Ritheesh36,

We don't plan to support flutter widgets in the near future.  The _App screen sharing_ and _App screen control_ is designed to native android applications.
