### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by Ritheesh36** [LogmeinRescue/Android-SDK#60]
Getting following logs after admin accept the connection.

W/System.err(13385): SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err(13385): SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err(13385): SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 4 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 1 line
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 3 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 29 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 3 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
D/Rescue event(13385): com.logmein.rescuesdk.api.session.event.ConnectingEvent@249fbfd
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 5 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 216 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 7 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 18 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 30 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 31 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 19 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/chatty  (13385): uid=10151(com.msf.gwc.dev) pool-13-thread- identical 24 lines
W/com.msf.gwc.de(13385): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
D/Rescue event(13385): com.logmein.rescuesdk.api.session.event.NetworkErrorEvent@d0f28b
D/Rescue event(13385): null

**Comment by tamasgyongyosi** [comment]
Hi @Ritheesh36 ,

Thank you for your feedback. Are you still getting this error?
