### ISSUE TITLE
Duplicated class - guava issue

### ISSUE THREAD

**Issue by jie-meng** [LogmeinRescue/Android-SDK#66]
Create Android project with newest Android studio, import LogmeinRescue android-sdk, sync and build will get this error:
```
Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules jetified-guava-19.0 (com.google.guava:guava:19.0) and jetified-listenablefuture-1.0 (com.google.guava:listenablefuture:1.0)
```
Because Android libraries use com.google.guava:listenablefuture:1.0, which will cause duplicated class with com.google.guava:guava:19.0 which used by LogmeinRescue android-sdk.

**Comment by tamasgyongyosi** [comment]
Hi @jie-meng , Thanks for sharing this issue. We do not experience anything similar. Could you please tell me exactly which android class uses this? Also, what dependencies are you using?

**Comment by tamasgyongyosi** [comment]
Hi @jie-meng is this something that might work for you: https://stackoverflow.com/questions/56639529/duplicate-class-com-google-common-util-concurrent-listenablefuture-found-in-modu ?

**Comment by jie-meng** [comment]
I use

> Hi @jie-meng , Thanks for sharing this issue. We do not experience anything similar. Could you please tell me exactly which android library uses this? Also, what dependencies are you using?

androidx.core:core-ktx:1.9.0
This is what the android project use which include ListenableFuture.

When I import
```
rescuesdkVersion = '3.8.8'
 implementation("com.logmein.rescuesdk:core:${rescuesdkVersion}@aar") {
        transitive = true
        exclude group: 'com.google.guava', module: 'guava'
    }
    implementation("com.logmein.rescuesdk:resources:${rescuesdkVersion}@aar") {
        transitive = false
    }
    implementation("com.logmein.rescuesdk:camerastreaming:${rescuesdkVersion}@aar") {
        transitive = true
    }
```
It'll cause the problem.
I tried to excude the guava 19 from logmein library, then it'll crash the app when I create session.

Use ```implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava' ``` it all works, thanks!
