### ISSUE TITLE
mediaclientlibjava-release v17.0.3.6296 missing from maven repo

### ISSUE THREAD

**Issue by cswagner** [LogmeinRescue/Android-SDK#71]
mediaclientlibjava-release v17.0.3.6296 seems to be missing from the [maven repo](https://github.com/LogmeinRescue/Android-SDK/tree/master/maven/repository/com/logmein/media/mediaclientlibjava-release). That version is referenced by other dependencies (e.g., [camerastreaming v3.9.4](https://github.com/LogmeinRescue/Android-SDK/blob/master/maven/repository/com/logmein/rescuesdk/camerastreaming/3.9.4/camerastreaming-3.9.4.pom#L96)).

Could mediaclientlibjava-release v17.0.3.6296 be added to the maven repo?

**Comment by tbalogh** [comment]
Hi @cswagner ,

I added the missing dependency to the repository. Could you verify if the issue has been resolved?

Best,
Tamas

**Comment by cswagner** [comment]
Hi @tbalogh, I see the dependency now. That should resolve this issue. Thank you!
