### ISSUE TITLE
'Copied to clipboard' system popup on Android 13 and above

### ISSUE THREAD

**Issue by christomaliyekkal** [LogmeinRescue/Android-SDK#75]
After starting camera share and canceling it, we are getting a copied to clipboard message.

This is a feature introduced in Android 13 - https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#Feedback

But here it is showing even without doing a copy paste. 
Issue can be reproduced on the example app you have provided.

https://github.com/LogmeinRescue/Android-SDK/assets/4237871/3b73ffbb-ac76-436b-a57f-fb8338ec3c09

This popup message should not appear when copy paste feature is not used.

**Comment by tamasgyongyosi** [comment]
Hi @christomaliyekkal  ,

Thank you for bringing this to our attention. What version of Rescue SDK are you using?

Best,
Tamas

**Comment by christomaliyekkal** [comment]
We are using 3.8.8. But I believe your example app should be using the latest

**Comment by tamasgyongyosi** [comment]
@christomaliyekkal please use the latest version https://github.com/LogmeinRescue/Android-SDK/releases/tag/3.9.6. This issue has already been fixed. Unfortunately the example app uses an old version of the SDK.

**Comment by christomaliyekkal** [comment]
Issue got fixed with 3.9.6. Thank you!
