### ISSUE TITLE
Receiving FlashLight Turned Off Event after Camera Streaming Paused Event

### ISSUE THREAD

**Issue by sarathrda** [LogmeinRescue/Android-SDK#9]
Once after the Camera streaming is started, if the streaming is Paused while Flash Light is ON, `CameraStreamingPausedEvent` is received and then `FlashlightTurnedOffEvent` is received.

**STEPS TO REPRODUCE**

- Initiate the Camera Streaming session
- Accept the Incoming request in the Technician console
- Once after the Session is started, switch on the Flash Light.
- Now `Pause` the camera streaming in the Android application
- Observe that `CameraStreamingPausedEvent` is received first, before the `FlashLightTurnedOff` event is received.

In this case, from the UI part, it is difficult to identify if the Session is Paused, before letting the User to enable the Flash Light again.

Similarly through the `Producers`, for a new Events Handler, the order of events received is as follows:

- ConnectedEvent
- FlashLightTurnedOnEvent
- CameraStreamingResumedEvent
- CameraStreamingStartedEvent

Even in this case, the `FlashLightTurnedOnEvent` should be at the end or at least after `CameraStreamingResumedEvent`.

Similarly, when in `CameraStreamingPausedEvent` state, for a new Events Handler, the order of events received is as follows:

- ConnectedEvent
- CameraStreamingPausedEvent
- CameraStreamingStartedEvent

The `CameraStreamingStartedEvent` at the end confuses the current state again.

**Comment by tbalogh** [comment]
Dear Sarath,

We will review this issue and get in touch with you shortly.

Thank you for bringing this to our attention.

Tamas

**Comment by balazsbanyai** [comment]
Hello, 

The ordering of the produced events should follow the order of dispatching. We've confirmed the ordering issue that you're experiencing, and we're working on a fix.

On the other hand we suggest that it is always a best-practice to create separate subscribers to event "families" (eg. ConnectionEvent, ChatMessageEvent are separate families), that can handle the different kinds of events independently from other event families. 
Please let us know if you can work this issue around using this approach, or this issue still blocks you from delivering, so that we can prioritize.

Thank you very much for your patience.

**Comment by balazsbanyai** [comment]
Hello, 

We released a new version of the SDK (#16 ), where the ordering of produced the produced events will follow the order of the original dispatch. Please confirm that this addresses your problem.

We're still waiting for your feedback regarding the order of CameraStreamingPausedEvent and FlashlightTurnedOffEvent, whether you could work this issue around using separate subscribers?

**Comment by sarathrda** [comment]
Hello @balazsbanyai ,

We have tried to have separate Subscribers for Flash and Streaming related events, and still we are receiving the events in the unexpected order only. (i.e., CameraStreamingPausedEvent is received and then FlashlightTurnedOffEvent).

Meanwhile we have verified the Fixes for the other two scenarios mentioned above, in the latest SDK version(3.2.5).

Thanks.
